 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
Usage: python -m flask run [OPTIONS]
Try 'python -m flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/mnt/c/Users/premc/OneDrive/Documentos/Monitoring&Logging/INFO8985-25S-Monitoring-Logging/monitoring-tracing-main/app.py", line 5, in <module>
    from fastapi.encoders import jsonable_encoder
ModuleNotFoundError: No module named 'fastapi'

Usage: python -m flask run [OPTIONS]
Try 'python -m flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/mnt/c/Users/premc/OneDrive/Documentos/Monitoring&Logging/INFO8985-25S-Monitoring-Logging/monitoring-tracing-main/app.py", line 5, in <module>
    from fastapi.encoders import jsonable_encoder
ModuleNotFoundError: No module named 'fastapi'

